import path from 'node:path';
import ts from 'typescript';
import type { AiContractGeneratedData } from './ai-contract.types';

export type {
  AiContractGeneratedBlock,
  AiContractGeneratedData,
  AiContractGeneratedMethod,
} from './ai-contract.types';

const DTS_CONFIG_FILE = 'tsconfig.dts.json';
const DECLARATION_ROOTS = [
  'src/dataset.ts',
  'src/format.ts',
  'src/types.ts',
  'src/generator/factory.ts',
  'src/generator/numbers.ts',
  'src/generator/types.ts',
] as const;

const HEADER_DECLARATIONS = [
  ['generator/factory.d.ts', 'SeedInput'],
  ['types.d.ts', 'OjProfile'],
  ['dataset.d.ts', 'MaybePromise'],
  ['types.d.ts', 'DebugOptions'],
  ['types.d.ts', 'WeightOption'],
  ['types.d.ts', 'GraphType'],
  ['types.d.ts', 'GraphOptions'],
  ['types.d.ts', 'TreeType'],
  ['types.d.ts', 'TreeOptions'],
  ['types.d.ts', 'BinaryTreeType'],
  ['types.d.ts', 'BinaryTreeOptions'],
  ['generator/numbers.d.ts', 'SequenceOptions'],
  ['format.d.ts', 'FormatAtom'],
  ['format.d.ts', 'FormatLine'],
  ['format.d.ts', 'FormatTable'],
  ['format.d.ts', 'FormatGrid'],
  ['format.d.ts', 'FormatRaw'],
  ['format.d.ts', 'FormatNode'],
  ['format.d.ts', 'FormatDocument'],
] as const;

const DATASET_DECLARATIONS = [
  ['dataset.d.ts', 'DatasetGenerateContext'],
  ['dataset.d.ts', 'DatasetValidationContext'],
  ['dataset.d.ts', 'DatasetValidationResult'],
  ['dataset.d.ts', 'DatasetValidationReturn'],
  ['dataset.d.ts', 'DatasetStaticCase'],
  ['dataset.d.ts', 'DatasetGeneratedCase'],
  ['dataset.d.ts', 'DatasetCase'],
  ['dataset.d.ts', 'DatasetConfig'],
  ['dataset.d.ts', 'Dataset'],
  ['dataset.d.ts', 'defineDataset'],
] as const;

const OMITTED_GENERATOR_METHODS = new Set(['withRng', 'resetRng']);

export function buildAiContractGeneratedData(projectRoot = process.cwd()): AiContractGeneratedData {
  const outputs = emitDeclarationFiles(projectRoot);
  const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
    removeComments: true,
  });

  const headerDeclarations = HEADER_DECLARATIONS.map(([fileName, declarationName]) =>
    extractNamedDeclarationBlock(outputs, printer, fileName, declarationName),
  );

  const datasetDeclarations = DATASET_DECLARATIONS.map(([fileName, declarationName]) =>
    extractNamedDeclarationBlock(outputs, printer, fileName, declarationName),
  );

  const formatSource = getDeclarationSourceFile(outputs, 'format.d.ts');
  const generatorSource = getDeclarationSourceFile(outputs, 'generator/types.d.ts');

  const fmtMethods = extractFmtMethods(formatSource, printer);
  const { generatorMethods, baseMethods, charsetProperties } = extractGeneratorSurface(generatorSource, printer);

  return {
    headerDeclarations,
    datasetDeclarations,
    fmtMethods,
    generatorMethods,
    baseMethods,
    charsetProperties,
  };
}

export function renderAiContractGeneratedSource(data: AiContractGeneratedData): string {
  return [
    '// Generated by scripts/build-ai-contract.ts',
    '// Do not edit this file by hand.',
    '',
    "import type { AiContractGeneratedData } from './ai-contract.types';",
    '',
    `export const AI_CONTRACT_GENERATED: AiContractGeneratedData = ${JSON.stringify(data, null, 2)} as const;`,
    '',
  ].join('\n');
}

function emitDeclarationFiles(projectRoot: string): Map<string, string> {
  const configPath = path.join(projectRoot, DTS_CONFIG_FILE);
  const configFile = ts.readConfigFile(configPath, ts.sys.readFile);

  if (configFile.error) {
    throw new Error(formatDiagnostics([configFile.error]));
  }

  const parsedConfig = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    projectRoot,
    {
      declaration: true,
      declarationMap: false,
      emitDeclarationOnly: true,
      noEmit: false,
    },
    configPath,
  );

  if (parsedConfig.errors.length > 0) {
    throw new Error(formatDiagnostics(parsedConfig.errors));
  }

  const rootNames = DECLARATION_ROOTS.map(fileName => path.join(projectRoot, fileName));
  const program = ts.createProgram({
    rootNames,
    options: parsedConfig.options,
  });

  const preEmitDiagnostics = ts.getPreEmitDiagnostics(program);
  if (preEmitDiagnostics.length > 0) {
    throw new Error(formatDiagnostics(preEmitDiagnostics));
  }

  const outDir = path.resolve(projectRoot, parsedConfig.options.outDir ?? 'dist');
  const outputs = new Map<string, string>();
  const emitResult = program.emit(
    undefined,
    (fileName, text) => {
      if (!fileName.endsWith('.d.ts')) return;
      const relativePath = normalizePath(path.relative(outDir, fileName));
      outputs.set(relativePath, text);
    },
    undefined,
    true,
  );

  if (emitResult.diagnostics.length > 0) {
    throw new Error(formatDiagnostics(emitResult.diagnostics));
  }

  return outputs;
}

function getDeclarationSourceFile(outputs: Map<string, string>, fileName: string): ts.SourceFile {
  const text = outputs.get(fileName);
  if (!text) {
    throw new Error(`Missing emitted declaration file: ${fileName}`);
  }
  return ts.createSourceFile(fileName, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
}

function extractNamedDeclarationBlock(
  outputs: Map<string, string>,
  printer: ts.Printer,
  fileName: string,
  declarationName: string,
): AiContractGeneratedBlock {
  const sourceFile = getDeclarationSourceFile(outputs, fileName);
  const node = findNamedDeclaration(sourceFile, declarationName);

  return {
    name: declarationName,
    declarationLines: printNodeLines(node, sourceFile, printer),
  };
}

function findNamedDeclaration(sourceFile: ts.SourceFile, declarationName: string): ts.Statement {
  for (const statement of sourceFile.statements) {
    if (
      (ts.isTypeAliasDeclaration(statement)
        || ts.isInterfaceDeclaration(statement)
        || ts.isFunctionDeclaration(statement))
      && statement.name?.text === declarationName
    ) {
      return statement;
    }
  }

  throw new Error(`Missing declaration '${declarationName}' in ${sourceFile.fileName}`);
}

function extractFmtMethods(sourceFile: ts.SourceFile, printer: ts.Printer): AiContractGeneratedMethod[] {
  const statement = sourceFile.statements.find(item =>
    ts.isVariableStatement(item)
      && item.declarationList.declarations.some(declaration =>
        ts.isIdentifier(declaration.name) && declaration.name.text === 'fmt',
      ),
  );

  if (!statement || !ts.isVariableStatement(statement)) {
    throw new Error(`Missing fmt declaration in ${sourceFile.fileName}`);
  }

  const declaration = statement.declarationList.declarations.find(item =>
    ts.isIdentifier(item.name) && item.name.text === 'fmt',
  );

  if (!declaration || !declaration.type || !ts.isTypeLiteralNode(declaration.type)) {
    throw new Error(`fmt declaration does not have a type literal in ${sourceFile.fileName}`);
  }

  return declaration.type.members.map(member => {
    if (!ts.isPropertySignature(member) || !member.type || !ts.isFunctionTypeNode(member.type)) {
      throw new Error(`Unsupported fmt member in ${sourceFile.fileName}`);
    }

    const name = getPropertyNameText(member.name);
    const methodSignature = ts.factory.createMethodSignature(
      undefined,
      member.name,
      member.questionToken,
      member.type.typeParameters,
      member.type.parameters,
      member.type.type,
    );
    const declarationLines = printNodeLines(methodSignature, sourceFile, printer);

    return {
      name,
      signature: firstDeclarationLine(declarationLines),
      declarationLines,
    };
  });
}

function extractGeneratorSurface(
  sourceFile: ts.SourceFile,
  printer: ts.Printer,
): {
  generatorMethods: AiContractGeneratedMethod[];
  baseMethods: AiContractGeneratedMethod[];
  charsetProperties: string[];
} {
  const interfaceNode = sourceFile.statements.find(item =>
    ts.isInterfaceDeclaration(item) && item.name.text === 'IGenerator',
  );

  if (!interfaceNode || !ts.isInterfaceDeclaration(interfaceNode)) {
    throw new Error(`Missing IGenerator declaration in ${sourceFile.fileName}`);
  }

  const generatorMethods: AiContractGeneratedMethod[] = [];
  const baseMethods: AiContractGeneratedMethod[] = [];
  const charsetProperties: string[] = [];
  const generatorIndexByName = new Map<string, number>();
  const baseIndexByName = new Map<string, number>();

  for (const member of interfaceNode.members) {
    if (ts.isMethodSignature(member)) {
      const name = getPropertyNameText(member.name);
      if (OMITTED_GENERATOR_METHODS.has(name)) continue;
      pushMethodSignature(generatorMethods, generatorIndexByName, name, member, sourceFile, printer);
      continue;
    }

    if (!ts.isPropertySignature(member) || !member.type || !ts.isTypeLiteralNode(member.type)) {
      continue;
    }

    const name = getPropertyNameText(member.name);
    if (name === 'CHARSET') {
      for (const nestedMember of member.type.members) {
        if (!ts.isPropertySignature(nestedMember)) continue;
        charsetProperties.push(getPropertyNameText(nestedMember.name));
      }
      continue;
    }

    if (name === 'base') {
      for (const nestedMember of member.type.members) {
        if (ts.isMethodSignature(nestedMember)) {
          const methodName = getPropertyNameText(nestedMember.name);
          pushMethodSignature(baseMethods, baseIndexByName, methodName, nestedMember, sourceFile, printer);
        }
      }
    }
  }

  return {
    generatorMethods,
    baseMethods,
    charsetProperties,
  };
}

function pushMethodSignature(
  methods: AiContractGeneratedMethod[],
  indexByName: Map<string, number>,
  name: string,
  signatureNode: ts.MethodSignature,
  sourceFile: ts.SourceFile,
  printer: ts.Printer,
): void {
  const declarationLines = printNodeLines(signatureNode, sourceFile, printer);
  const index = indexByName.get(name);

  if (index === undefined) {
    indexByName.set(name, methods.length);
    methods.push({
      name,
      signature: firstDeclarationLine(declarationLines),
      declarationLines,
    });
    return;
  }

  const existing = methods[index];
  methods[index] = {
    ...existing,
    declarationLines: [...existing.declarationLines, ...declarationLines],
  };
}

function printNodeLines(node: ts.Node, sourceFile: ts.SourceFile, printer: ts.Printer): string[] {
  return normalizePrintedDeclaration(
    printer.printNode(ts.EmitHint.Unspecified, node, sourceFile),
  ).split('\n');
}

function normalizePrintedDeclaration(text: string): string {
  return text
    .replace(/\r\n/g, '\n')
    .replace(/\bexport\s+declare\s+/g, 'export ')
    .trim();
}

function firstDeclarationLine(lines: readonly string[]): string {
  const line = lines.find(item => item.trim().length > 0);
  if (!line) {
    throw new Error('Method declaration lines are empty.');
  }
  return line.trim();
}

function getPropertyNameText(name: ts.PropertyName): string {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
    return name.text;
  }
  throw new Error(`Unsupported property name kind: ${ts.SyntaxKind[name.kind]}`);
}

function normalizePath(fileName: string): string {
  return fileName.split(path.sep).join('/');
}

function formatDiagnostics(diagnostics: readonly ts.Diagnostic[]): string {
  return ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCanonicalFileName: fileName => fileName,
    getCurrentDirectory: () => process.cwd(),
    getNewLine: () => '\n',
  });
}
